[build]
command = "npm run build"
publish = "build"

[build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  TERM = "xterm"

# run Cypress E2E tests
[[plugins]]
package = "netlify-plugin-cypress"
  [plugins.inputs]
    # skip the default tests before the deploy
    record = true
    spec = "cypress/integration/*"
  [plugins.inputs.postBuild]
    # run tests after the deploy
    enable = true