

[build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  TERM = "xterm"

[[redirects]]
from = "https://adoring-carson-eb5696.netlify.app/*"
to = "http://numbersapi.com/*"
status = 200
force = true



# run Cypress E2E tests
[[plugins]]
package = "netlify-plugin-cypress"
  [plugins.inputs]
    # skip the default tests before the deploy
    record = true
    spec = "cypress/integration/**"